backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("index.urls", namespace='index')),
    path("invoices/", include("invoices.urls",namespace='invoices'))
]

if settings.DEBUG:
    # Dev-only Serve
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/index/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    # path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout")
]

backend/invoices/urls.py
from django.urls import path
from . import views

app_name = 'invoices'
urlpatterns = [
    path("", views.index, name="index"),
    path("generate/", views.generate, name="generate"),
    path("pdf/<int:invoice_number>", views.view_invoice_as_pdf, name="view_invoice_as_pdf"),
]

backend/invoices/models.py
import re
from django.db import models
from phonenumber_field.modelfields import PhoneNumber, PhoneNumberField
from .utility import add_leading_zeros



class Address(models.Model):
    name = models.CharField(max_length=256, default='Source Bakery', blank=True)
    address = models.CharField(max_length=128, default=' 8601 Jefferson Street #101', blank=True)
    city = models.CharField(max_length=128, default='Tolleson', blank=True)
    state = models.CharField(max_length=2, default='AZ', blank=True)
    zip = models.CharField(max_length=5, default='85353', blank=True)
    zip_extension = models.CharField(max_length=5, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name_plural = "addresses"
        
    def __str__(self):
        return self.name + " | " + self.address + ', ' +  self.city + ', ' +  self.state + ' ' + self.zip

    def get_full_address(self):
        address = self.address + ', ' +  self.city + ', ' +  self.state + ' ' + self.zip
        return address
    
    
    

class Company(models.Model):
    name = models.CharField(max_length=256, default='Aaron Trucking, Inc.', blank=True)
    brand = models.ImageField(upload_to='companies/brands')
    phone = PhoneNumberField(null=False, blank=False, unique=True)
    phone_extension = models.CharField(max_length=10, blank=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='housing_companies')
    billing_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='billing_companies')
    email = models.EmailField(max_length=254)

    class Meta:
        verbose_name_plural = "companies"

    def __str__(self):
        return self.name

class Truck(models.Model):
    number = models.CharField(max_length=256, default='771')

    def __str__(self):
        return self.number

class Trailer(models.Model):
    number = models.CharField(max_length=256, default='7847X')

    def __str__(self):
        return self.number

class Driver(models.Model):
    first_name = models.CharField(max_length=256, default='Aaron')
    last_name = models.CharField(max_length=256, default='Zepeda')

    def __str__(self):
        return self.first_name + " " + self.last_name

class Trip(models.Model):
    trip_number = models.PositiveIntegerField(unique=True)
    delivery_date = models.DateField(auto_now_add=False, help_text="Automatically filled in")
    delivery_number = models.PositiveIntegerField()
    truck = models.ForeignKey(Truck, on_delete=models.CASCADE, related_name='trips')
    trailer = models.ForeignKey(Trailer, on_delete=models.CASCADE, related_name='trips')
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, related_name='trips')
    ship_from_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='shipped_from_invoices')
    ship_to_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='shipped_to_invoices')
    attachment = models.FileField(upload_to='trips/attachments/')

    def __str__(self):
        return "TRIP #" + str(self.trip_number)

class Invoice(models.Model):

    TERMS_CHOICE = (
        (7, "Net 7"),
        (15, "Net 15"),
        (30, "Net 30"),
        (60, "Net 60"),
        (90, "Net 90"),
        (120, "Net 120"),
    )

    invoicing_party = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='invoicing_invoices')
    invoiced_party = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='invoiced_invoices')
    invoice_number = models.PositiveIntegerField(unique=True)
    terms = models.IntegerField(choices=TERMS_CHOICE, default=30)
    date = models.DateField(auto_now_add=False, help_text="Automatically filled in")
    due_date = models.DateField(auto_now_add=False, help_text="Automatically filled in")
    sales_number = models.PositiveIntegerField()
    trip = models.OneToOneField(Trip, on_delete=models.CASCADE)
    rate = models.DecimalField(max_digits=7, decimal_places=2)
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ['invoice_number']

    def __str__(self):
        return "INVOICE #" + str(self.invoice_number)

    def get_leading_zeros_invoice_number(self):
        LEADING_ZEROS = 6
        return add_leading_zeros(self.invoice_number, LEADING_ZEROS)
    
    def get_pdf_name(self):
        regex = re.compile('[^a-zA-Z]')
        clean_name = regex.sub('', self.invoicing_party.name).upper() + "_Invoice_" + self.get_leading_zeros_invoice_number()
        return clean_name

    def create_object_from_form(request):
        invoice_number = self.cleaned_data["invoice_number"]
        print(invoice_number)

backend/invoices/forms.py
from django import forms
from django.forms.models import fields_for_model
from datetime import datetime, timedelta
from .ocr import read_bill_of_lading
from .models import (
    Address,
    Company,
    Truck,
    Driver,
    Trip,
    Invoice,
)


DEFAULT_DRIVER = { 'first_name' : 'Aaron', 'last_name' : 'Zepeda' }
DEFAULT_INVOICING_PARTY = "Aaron Freight, Inc."
DEFAULT_INVOICED_PARTY = "Sweetener Products Company"
DEFAULT_TERMS = 30

# Create your forms here.
class BillOfLadingToTripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = (
            'trailer',
            'ship_to_address',
        )
        labels = {
            "ship_to_address": "Ship-To-Address"
        }


class BillOfLadingToInvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = (
            'rate',
            'notes',
        )

    def generate_trip(invoice_number, trailer, ship_to_address):
        truck = Truck.objects.filter(number=771).first()
        driver = Driver.objects.filter(first_name=DEFAULT_DRIVER['first_name'], last_name=DEFAULT_DRIVER['last_name']).first()
        ship_from_address = Address.objects.filter(name=DEFAULT_INVOICED_PARTY).first()

        trip = Trip(
            trip_number = invoice_number,
            truck = truck,
            trailer = trailer,
            driver = driver,
            ship_from_address = ship_from_address,
            ship_to_address = ship_to_address
        )

        return trip

    def generate_invoice(invoice_number, bill_of_lading, trip, rate, notes, optional_sales_number, optional_delivery_number, optional_delivery_date):

        mapped_bill_of_lading = read_bill_of_lading(bill_of_lading.file)

        if optional_sales_number is None:
            sales_number = mapped_bill_of_lading['sales_number']
        else:
            sales_number = optional_sales_number

        if optional_delivery_number is None:
            trip.delivery_number = mapped_bill_of_lading['delivery_number']
        else:
            trip.delivery_number = optional_delivery_number

        if optional_delivery_date is None:
            base_date = datetime.strptime(mapped_bill_of_lading['delivery_date'], '%m/%d/%y').date()
        else:
            base_date = optional_delivery_date
        invoice_date = base_date
        trip.delivery_date = invoice_date
        due_date = base_date + timedelta(days=DEFAULT_TERMS)
            
        trip.attachment = bill_of_lading


        invoicing_party = Company.objects.filter(name=DEFAULT_INVOICING_PARTY).first()
        invoiced_party = Company.objects.filter(name=DEFAULT_INVOICED_PARTY).first()

        invoice = Invoice(
            invoicing_party = invoicing_party,
            invoiced_party = invoiced_party,
            invoice_number = invoice_number,
            terms = DEFAULT_TERMS,
            date = invoice_date,
            due_date = due_date,
            sales_number = sales_number,
            trip = trip,
            rate = rate,
            notes = notes
        )

        return invoice

        

class BillOfLadingForm(forms.Form):
    bill_of_lading = forms.FileField()
    optional_invoice_number = forms.IntegerField(required=False, label="Invoice Number")
    optional_sales_number = forms.IntegerField(required=False, label="Sales Number")
    optional_delivery_number = forms.IntegerField(required=False, label="Delivery Number")
    optional_delivery_date = forms.DateField(required=False, label="Delivery Date")
    forms.DateField()

backend/invoices/views.py
import os, tempfile

from django.http import HttpResponse, HttpResponse ,HttpResponseRedirect, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.exceptions import PermissionDenied, ValidationError
from django.template.loader import get_template
from django.db.models import Max
from django.contrib.auth.decorators import login_required
from django.conf import settings

from PyPDF2 import PdfReader, PdfWriter, Transformation, PageObject
from PyPDF2.generic import RectangleObject
from PyPDF2 import PaperSize

from .models import (
    Invoice,
    Trip
)
from .forms import (
    BillOfLadingToTripForm,
    BillOfLadingToInvoiceForm,
    BillOfLadingForm,
)

from weasyprint import HTML, CSS
from weasyprint.text.fonts import FontConfiguration


def pdf(request, invoice):
    args = {
        "invoice" : invoice,
        "leading_zeros_invoice_number" : invoice.get_leading_zeros_invoice_number(),
    }

    # Get the template
    template = get_template('invoices/invoice_as_pdf.html')
    
    # Render the template
    rendered_html = template.render(args)

    # Create a temporary file to store the PDF
    with tempfile.NamedTemporaryFile(delete=False) as generated_invoice_pdf, tempfile.NamedTemporaryFile(delete=False) as complete_invoice_pdf, tempfile.NamedTemporaryFile(delete=False) as modified_attachment:
        # Generate the PDF using WeasyPrint
        font_config = FontConfiguration()
        invoice_css = CSS(settings.BASE_DIR / 'invoices/static/invoices/css/invoice.css', font_config=font_config)
        bootstrap_css = CSS(url='https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css')
        HTML(string=rendered_html, base_url=request.build_absolute_uri()).write_pdf(target=generated_invoice_pdf, stylesheets=[bootstrap_css,invoice_css],font_config=font_config)

        # Adjust attachment
        invoice_attachment = invoice.trip.attachment.file.open('r')
        pdf_reader = PdfReader(invoice_attachment)
        pdf_writer = PdfWriter()

        A4_w = PaperSize.A4.width
        A4_h = PaperSize.A4.height

        # Iterate through each page of the existing PDF
        for page in pdf_reader.pages:
            # resize page to fit *inside* A4
            h = float(page.mediabox.height)
            w = float(page.mediabox.width)
            scale_factor = min(A4_h/h, A4_w/w)

            transform = Transformation().scale(scale_factor,scale_factor).translate(0, 0)
            page.add_transformation(transform)

            page.cropbox = RectangleObject((0, 0, A4_w, A4_h))

            # merge the pages to fit inside A4

            # prepare A4 blank page
            page_A4 = PageObject.create_blank_page(width = A4_w, height = A4_h)
            page.mediabox = page_A4.mediabox
            page_A4.merge_page(page)

            # Add the modified page to the new PDF
            pdf_writer.add_page(page)
        pdf_writer.write(modified_attachment)
        pdf_writer.close()

        # Combine PDF with attachment
        merger = PdfWriter()
        for pdf in [generated_invoice_pdf, modified_attachment]:
            merger.append(pdf)
        merger.write(complete_invoice_pdf)
        merger.close()


    # Read the PDF file
    with open(complete_invoice_pdf.name, 'rb') as pdf_file:
        response = HttpResponse(pdf_file.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'filename="' + invoice.get_pdf_name() + '.pdf"'
        return response
    



@login_required
def index(request):
    args = {
        'invoices' : Invoice.objects.all().order_by('-date')
    }

    return render(request, 'invoices/home.html', args)

@login_required
def generate(request):
    if request.method == 'POST':
        trip_form = BillOfLadingToTripForm(request.POST, request.FILES)
        invoice_form = BillOfLadingToInvoiceForm(request.POST , request.FILES)
        bill_of_lading_form = BillOfLadingForm(request.POST, request.FILES)

        # check whether it's valid:
        if trip_form.is_valid() and invoice_form.is_valid() and bill_of_lading_form.is_valid() and request.user.is_authenticated:
            invoice_number = bill_of_lading_form.cleaned_data["optional_invoice_number"]
            # Check if invoice number is given, if not then set it as new max
            if invoice_number is None:
                max = Invoice.objects.aggregate(Max('invoice_number')).get('invoice_number__max')
                if max is None:
                    invoice_number = 1
                else:
                    invoice_number = max + 1
            elif Invoice.objects.filter(invoice_number=invoice_number).exists():
                raise Http404("An invoice with that number already exists.")
            
            optional_sales_number = bill_of_lading_form.cleaned_data["optional_sales_number"]
            optional_delivery_number = bill_of_lading_form.cleaned_data["optional_delivery_number"]
            optional_delivery_date = bill_of_lading_form.cleaned_data["optional_delivery_date"]

                
            bill_of_lading = bill_of_lading_form.cleaned_data["bill_of_lading"]
            trailer = trip_form.cleaned_data["trailer"]
            ship_to_address = trip_form.cleaned_data["ship_to_address"]
            rate = invoice_form.cleaned_data["rate"]
            notes = invoice_form.cleaned_data["notes"]

            trip = BillOfLadingToInvoiceForm.generate_trip(
                invoice_number,
                trailer, 
                ship_to_address
            )

            invoice = BillOfLadingToInvoiceForm.generate_invoice(
                invoice_number,
                bill_of_lading,
                trip,
                rate,
                notes,
                optional_sales_number,
                optional_delivery_number,
                optional_delivery_date,
            )

            if 'generate_and_save' in request.POST:
                try:
                    old_trip = Trip.objects.get(trip_number=trip.trip_number)
                    old_trip.delete()
                except Trip.DoesNotExist:
                    ...
                try:
                    trip.save()
                except ValidationError as e:
                    raise Http404("Bill of lading could not be read. ERROR: " + str(e))
                
                try:
                    old_invoice = Invoice.objects.get(invoice_number=invoice.invoice_number)
                    old_invoice.delete()
                except Invoice.DoesNotExist:
                    ...
                try:
                    invoice.save()
                except ValidationError as e:
                    trip.delete()
                    raise Http404("Invoice could not be generated. ERROR: " + str(e))

                reverse_view_url = reverse('invoices:view_invoice_as_pdf', kwargs={'invoice_number': invoice.invoice_number})
                return HttpResponseRedirect(reverse_view_url)
            elif 'generate' in request.POST:
                ...

            return pdf(request, invoice)
    else:
        trip_form = BillOfLadingToTripForm()
        invoice_form = BillOfLadingToInvoiceForm()
        bill_of_lading_form = BillOfLadingForm()

    args = {
        "trip_form" : trip_form,
        "invoice_form" : invoice_form,
        "bill_of_lading_form" : bill_of_lading_form,
    }

    return render(request, 'invoices/generate.html', args)


@login_required
def view_invoice_as_pdf(request, invoice_number):
    try:
        invoice = Invoice.objects.get(invoice_number=invoice_number)

        # if not request.user.is_authenticated:
        #     raise PermissionDenied
            
    except Invoice.DoesNotExist:
        raise Http404("Invoice does not exist.")
    except Invoice.MultipleObjectsReturned:
        raise Http404("More than one invoice with the same number exists.")
    
    return pdf(request, invoice)

backend/invoices/templates/invoices/__base.html
{% load static %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Placeholder description.">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Bootstrap Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!--Custom CSS -->
    <link rel="stylesheet" href="{% static 'invoices/css/__global.css' %}">

    <!-- Homepage Title -->
    <title>Aaron Freight, Inc.</title>

    <!-- Favicons -->
    <link rel="shortcut icon" type="image/svg+xml" href="{% static 'invoices/images/favicon.svg' %}">

    <!-- The rest of the page's header -->
    {% block header %}
    {% endblock %}

  </head>



  <body class="position-relative">
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'invoices:index' %}">
          <img src="{% static 'invoices/images/brand-white.svg' %}" alt="Bootstrap" height="50" class="d-inline-block align-text-top">
        </a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ms-auto pe-5">
            <a class="nav-link active" aria-current="page" href="{% url 'invoices:index' %}">Invoices</a>
            <a class="nav-link link-light" href="{% url 'invoices:generate' %}">Generate</a>
            <a class="nav-link link-light" href="/admin">Admin</a>
            <a class="nav-link link-light" href="{% url 'index:logout' %}s">Logout</a>
          </div>
        </div>
      </div>
    </nav>
    <div class="py-1" style="background-color: #DA1408;"></div>
    <!-- End Navigation bar -->

    <!-- Body -->
    <div id="bg-white" style="padding-bottom: 10rem;">
      {% block body %}
      {% endblock %}
    </div>
    <!-- End body -->

    <!-- Footer -->
    <footer class="container-fluid position-absolute bottom-0 start-0 bg-dark p-0 m-0">
      <div class="text-light d-flex justify-content-center align-items-center py-4">
        <!-- Github -->
        <a href="https://github.com/aaronzepeda" class="btn btn-circle btn-outline-light d-flex justify-content-center align-items-center">
          <i class="bi bi-github" style="font-size: 1.5rem;"></i>
        </a>
      </div>
      <div class="text-center text-light py-4" style="background-color: rgba(0, 0, 0, 1);">
        © 2020 Copyright:
        <a class="link-light" href="https://aaronzepeda.com">aaronzepeda.com</a>
      </div>
    </footer>
    <!-- End Footer -->


    <!-- Bootstrap Js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>


</html>

backend/invoices/templates/invoices/generate.html
{% extends 'invoices/__base.html' %}
{% load static %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
{% endblock %}

{% block body %}
  <!-- Title -->
  <div class="container-fluid">
    <div class="py-2"></div>
    <div class="text-center text-dark pt-4 pb-2">
      <h1><strong>Invoice Generator</strong></h1>
    </div>
    <div class="text-center text-secondary pt-2 pb-4">
      Please fill out the information below to generate an invoice.
    </div>
    <div class="row py-2">
      <div class="col"></div>
      <div class="col border-bottom"></div>
      <div class="col"></div>
    </div>
  </div>
  <!-- End Title -->

  
  <div class="container-sm py-4">
    <form enctype="multipart/form-data" action="#" method="post">
      {% csrf_token %}
      
      <!-- Optional Invoice Number Field -->
      {% bootstrap_label bill_of_lading_form.optional_invoice_number.label label_class='mb-0' %}
      <br>
      {% bootstrap_label "Leave empty to automatically determine the next invoice number." label_class='form-text mb-1' %}
      {% bootstrap_field bill_of_lading_form.optional_invoice_number show_label=False %}

      <!-- Optional Sales Number Field -->
      {% bootstrap_label bill_of_lading_form.optional_sales_number.label label_class='mb-0' %}
      <br>
      {% bootstrap_label "Leave empty to scan the sales number." label_class='form-text mb-1' %}
      {% bootstrap_field bill_of_lading_form.optional_sales_number show_label=False %}

      <!-- Optional Delivery Number Field -->
      {% bootstrap_label bill_of_lading_form.optional_delivery_number.label label_class='mb-0' %}
      <br>
      {% bootstrap_label "Leave empty to scan the delivery number." label_class='form-text mb-1' %}
      {% bootstrap_field bill_of_lading_form.optional_delivery_number show_label=False %}

      <!-- Optional Delivery Date Field -->
      {% bootstrap_label bill_of_lading_form.optional_delivery_date.label label_class='mb-0' %}
      <br>
      {% bootstrap_label "Leave empty to scan the delivery date. Otherwise provide date in DD/MM/YY" label_class='form-text mb-1' %}
      {% bootstrap_field bill_of_lading_form.optional_delivery_date show_label=False %}
      
      <!-- Bill of Lading Field -->
      {% bootstrap_field bill_of_lading_form.bill_of_lading %}
      <!-- Trailer Field -->
      {% bootstrap_field trip_form.trailer %}
      
      <!-- Ship-to-address Field -->
      {% bootstrap_field trip_form.ship_to_address %}
      <!-- Rate Field -->
      {% bootstrap_field invoice_form.rate addon_before="$" placeholder='1000' addon_after=".00" %}
      <!-- Notes Field -->
      {% bootstrap_field invoice_form.notes %}
        
      <div class="row d-flex align-items-center justify-content-center">
        <div class="col-sm-auto text-center">{% bootstrap_button button_type="submit" content="Generate Only" size='md' name="generate" button_class="btn-outline-secondary my-1" %}</div>
        <div class="col-sm-auto text-center">{% bootstrap_button button_type="submit" content="Generate and Save" size='md' name="generate_and_save" button_class="btn-primary my-1" %}</div>
        
        
      </div>
    </form>
  </div>

{% endblock %}

backend/invoices/templates/invoices/home.html
{% extends 'invoices/__base.html' %}
{% load static %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
{% endblock %}

{% block body %}
  <!-- Title -->
  <div class="container-fluid">
    <div class="py-2"></div>
    <div class="text-center text-dark pt-4 pb-2">
      <h1><strong>Your Invoices</strong></h1>
    </div>
    <div class="text-center text-secondary pt-2 pb-4">
      Click on an invoice to view as PDF format.
    </div>
    <div class="row py-2">
      <div class="col"></div>
      <div class="col border-bottom"></div>
      <div class="col"></div>
    </div>
  </div>
  <!-- End Title -->

  <div class="container-sm py-4">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="col-1">#</th>
          <th class="col">Description</th>
          <th class="col-2">Date</th>
          <th class="col-2">Due Date</th>
          <th class="col-1">Download</th>
        </tr>
      </thead>
      <tbody>
        {% for invoice in invoices %}
        <tr>
          <td>{{ invoice.invoice_number }}</td>
          <td>{{ invoice.trip.ship_from_address.name }}, {{ invoice.trip.ship_from_address.state }} to {{ invoice.trip.ship_to_address.name }}, {{ invoice.trip.ship_to_address.state }}</td>
          <td>{{ invoice.date|date:'n/d/y' }}</td>
          <td>{{ invoice.due_date|date:'n/d/y' }}</td>
          <td><a href="{% url 'invoices:view_invoice_as_pdf' invoice_number=invoice.invoice_number %}">PDF</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}