backend/backend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("index.urls", namespace='index')),
    path("invoices/", include("invoices.urls",namespace='invoices'))
]

if settings.DEBUG:
    # Dev-only Serve
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/index/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path("", views.index, name="index"),
    path("home", views.home, name="home"),
    # path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout")
]

backend/index/templates/index/__base.html
{% load static %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Placeholder description.">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Bootstrap Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!--Custom CSS -->
    <link rel="stylesheet" href="{% static 'index/css/__global.css' %}">

    <!-- Homepage Title -->
    <title>Aaron Zepeda's Website</title>

    <!-- Favicons -->
    <link rel="shortcut icon" type="image/svg+xml" href="{% static 'index/images/brand-white.svg' %}">

    <!-- The rest of the page's header -->
    {% block header %}
    {% endblock %}

  </head>



  <body class="position-relative">
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-dark py-3" style="background-color: #C113E8;">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'invoices:index' %}">
          <img src="{% static 'index/images/brand-white.svg' %}" alt="Bootstrap" height="25" class="d-inline-block align-text-top">
          <strong>AaronZepeda.com</strong> 
        </a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ms-auto pe-5">
            <a class="nav-link link-light" href="{% url 'invoices:index' %}">Aaron Freight, Inc.</a>
            {% if user.is_authenticated %}
              <a class="nav-link link-light" href="{% url 'index:logout' %}">Logout</a>
            {% else %}
              <a class="nav-link link-light" href="{% url 'index:login' %}">Login</a>
            {% endif %}
            
          </div>
        </div>
      </div>
    </nav>
    <!-- End Navigation bar -->

    <!-- Body -->
    <div id="bg-white" style="padding-bottom: 10rem;">
      {% block body %}
      {% endblock %}
    </div>
    <!-- End body -->

    <!-- Footer -->
    <footer class="container-fluid position-absolute bottom-0 start-0 bg-dark p-0 m-0">
      <div class="text-light d-flex justify-content-center align-items-center py-4">
        <!-- Github -->
        <a href="https://github.com/aaronzepeda" class="btn btn-circle btn-outline-light d-flex justify-content-center align-items-center">
          <i class="bi bi-github" style="font-size: 1.5rem;"></i>
        </a>
      </div>
      <div class="text-center text-light py-4" style="background-color: rgba(0, 0, 0, 1);">
        © 2020 Copyright:
        <a class="link-light" href="https://aaronzepeda.com">aaronzepeda.com</a>
      </div>
    </footer>
    <!-- End Footer -->


    <!-- Bootstrap Js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>


</html>

backend/index/templates/index/home.html
{% extends 'index/__base.html' %}
{% load static %}

{% block header %}
{% endblock %}

{% block body %}
  <!-- Title -->
  <div class="container-fluid">
    <div class="py-2"></div>
    <div class="text-center text-dark pt-4 pb-2">
      <h1><strong>Welcome!</strong></h1>
    </div>
    <div class="text-center text-secondary pt-2 pb-4">
      You've landed at aaronzepeda.com.
    </div>
    <div class="row py-2">
      <div class="col"></div>
      <div class="col border-bottom"></div>
      <div class="col"></div>
    </div>
  </div>
  <!-- End Title -->
{% endblock %}

backend/index/templates/index/login.html
{% extends 'index/__base.html' %}
{% load static %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
{% endblock %}

{% block body %}
  <!-- Title -->
  <div class="container-fluid">
    <div class="py-2"></div>
    <div class="text-center text-dark pt-4 pb-2">
      <h1><strong>Login</strong></h1>
    </div>
    <div class="text-center text-secondary pt-2 pb-4">
      Please enter your information below to login.
    </div>
    <div class="py-2"></div>
  </div>
  <!-- End Title -->
  
  <div class="container-sm py-4">
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form login_form %}   
      <button class="btn btn-primary" type="submit">Login</button>
    </form>
    <!-- <p class="text-center">Don't have an account? <a href="/register">Create an account</a>.</p> -->
  </div>
{% endblock %}

backend/index/templates/index/register.html
{% extends 'index/__base.html' %}
{% load static %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
{% endblock %}

{% block body %}
  <!-- Title -->
  <div class="container-fluid">
    <div class="py-2"></div>
    <div class="text-center text-dark pt-4 pb-2">
      <h1><strong>Register</strong></h1>
    </div>
    <div class="text-center text-secondary pt-2 pb-4">
      Please enter your information below to create a new account.
    </div>
    <div class="py-2"></div>
  </div>
  <!-- End Title -->

  <div class="container-sm py-4">
    <form method="POST">
      {% csrf_token %}
      {% bootstrap_form register_form %}                  
      <button class="btn btn-primary" type="submit">Register</button>
    </form>
    <p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
  </div>

{% endblock %}